[project]
name = "NexusDownloadFlow"
version = "2.0.0-SNAPSHOT"
author = "greg-ynx"
release-date = 2023-10-01
requires-python = ">=3.11"

[github]
owner = "greg-ynx"
repository = "https://github.com/greg-ynx/NexusDownloadFlow"

[python]
version = "3.11.5"
